# Generated by Django 3.2.5 on 2021-10-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('total_items', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_delivered', models.BooleanField()),
            ],
        ),
    ]
